CREATE TABLE berita (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul VARCHAR(200) NOT NULL,
    isi TEXT NOT NULL,
    tanggal_terbit DATE NOT NULL,
    jumlah_dilihat INTEGER NOT NULL DEFAULT 0,
    id_kategori INTEGER NOT NULL,

    CONSTRAINT fk_berita_kategori
        FOREIGN KEY (id_kategori)
        REFERENCES kategori (id)
);

INSERT INTO berita (judul, isi, tanggal_terbit, jumlah_dilihat, id_kategori)
SELECT
    'Berita Akademik ' || nomor,
    'Isi berita akademik nomor ' || nomor,
    DATE '2026-09-01' + (nomor - 1),
    nomor * 10,
    (SELECT id FROM kategori WHERE nama = 'Akademik')
FROM generate_series(1, 20) AS nomor;